services:
  Red-WS-Pub:
    build:
      context: .
      dockerfile: Red-WS-Publisher/Dockerfile
    container_name: Red-WS-Publisher
    ports:
      - "6379:6379"
    networks:
      - redis-net
services:  
  API-Nginx-Gateway:
  
networks:
  redis-net:
    driver: bridge
